# Config file for Air (https://github.com/cosmtrek/air)
# Run with: air -c .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./examples/simple/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", ".git", ".github", "scripts", "docs"]
  include_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  log = "air.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
  app = "white"

[misc]
  clean_on_exit = true