run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github
  skip-files:
    - ".*_test.go"
    - "mock_*.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - errorlint
    - exhaustivestruct
    - exportloopref
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - nlreturn
    - testpackage
    - wsl

  disable:
    - maligned
    - interfacer
    - scopelint
    - golint
    - gofumpt  # We use gofumpt separately

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 30
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/sachin-duhan/postal-go
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  godot:
    scope: declarations
    capital: false
  godox:
    keywords:
      - TODO
      - BUG
      - FIXME
      - HACK
  nestif:
    min-complexity: 4
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - goconst
    - path: examples/
      linters:
        - gochecknoinits
        - gochecknoglobals
        - exhaustivestruct
        - funlen
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    - linters:
        - stylecheck
        - golint
      text: "ST1000:"
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true